config/routes.rb
HomeWorks::Application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :users
  resource :sessions

  get 'welcome/index'

  root to: 'welcome#index'

end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :url, :imageable_id, :imageable_type
  belongs_to :imageable, polymorphic: :true
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :body, :published_at, :user_id
  belongs_to :user
  has_many :images, as: :imageable, dependent: :destroy

  scope :post_published, -> { where('published_at IS NOT NULL') }
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :firstname, :lastname, :username, :email, :birthday, :password, :password_confirmation
  attr_accessor :password
  attr_accessor :password_confirmation
  before_save :encrypt_password
  
  has_many :posts, dependent: :destroy
  has_many :images, as: :imageable, dependent: :destroy

  validates :email, uniqueness: true, presence: true
  validates :username, uniqueness: true, presence: true
  validates :password, length: { minimum: 8 }, presence: true

  scope :adult_users, -> { where('birthday < ?', 18.year.ago) }

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def authorize
    redirect_to log_in_path, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash[:error] = 'Invalid email or password'
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :user_resourse, only: [:show, :edit, :update]

  def new
    @user = User.new
  end

  def edit
    redirect_to root_path unless current_user
  end

  def update
    @user.update_attributes((params[:user]))
    redirect_to action: :show
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Signed up "
    else
      render 'new'
    end
  end

  private

  def user_resourse
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HomeWorks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'responsiveslides.min', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class = "container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<br>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">SoftCroup</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Blog', root_path %></li>
        <li><%= link_to 'About', root_path %></li>
      </ul>
      <ul class='nav navbar-nav navbar-right'>
        <% if current_user %>
          <li class="logut">
            Logged in as <%= current_user.email %>.
          </li>
          <li>
            <%= link_to 'Log out', logout_path %>
          </li>
        <% else %>
          <li>
            <%= link_to 'Sign up', signup_path %>
          </li>
          <li>
            <%= link_to 'Log In', login_path %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/users/new.html.erb
<%= render 'shared/header' %>
<br>
<div class='col-md-6 col-xs-12 col-xs-offset-3'>
  <h1>Sign Up</h1>
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class='error_messages'>
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= f.label :firstname %>
      <br>
      <%= f.text_field :firstname, autofocus: true, placeholder: 'firstname', required: true, class: 'form-control' %>
    </p>
    <p>
      <%= f.label :lastname %>
      <br>
      <%= f.text_field :lastname, autofocus: true, placeholder: 'lastname', required: true, class: 'form-control' %>
    </p>
     <p>
      <%= f.label :username %>
      <br>
      <%= f.text_field :username, autofocus: true, placeholder: 'username', required: true, class: 'form-control' %>
    </p>
    <p>
      <%= f.label :email %>
      <br>
      <%= f.text_field :email, autofocus: true, placeholder: 'Email', required: true, class: 'form-control' %>
    </p>
    <p>
      <%= f.label :birthday %><br>
      <%= f.date_select :birthday, :order => [:day, :month, :year] %>
    </p>
    <p>
      <%= f.label :password %>
      <br>
      <%= f.password_field :password, autocomplete: 'off', placeholder: 'password', required: true, class: 'form-control' %>
    </p>
    <p>
      <%= f.label :password_confirmation %>
      <br>
      <%= f.password_field :password_confirmation, autocomplete: 'off', placeholder: 'password_confirmation', required: true, class: 'form-control' %>
    </p>
    <br>
      <div class='clear'><%= f.submit 'Create user', class: 'btn btn-success' %></div>
  <% end %>
</div>

app/views/welcome/index.html.erb
<%= render 'shared/header' %>